default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=120, --check]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
      args: ["--max-line-length=120"]
      
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--ignore-missing-imports, --show-column-numbers, --disallow-untyped-defs, --disallow-untyped-calls]